// client.config.ts
// Generated by Claude for AL Downtown
// Studio Ouro — 2026-02-20

export const client = {

  meta: {
    title: "AL Downtown — Webbdesign & Digitala tjänster i hela Sverige",
    description: "AL Downtown bygger snabba, SEO-optimerade webbsidor för småföretag i hela Sverige. Kreativ design, digital marknadsföring och konsultation sedan 2019.",
    language: "sv",
    token: "",
    domain: "",
  },

  brand: {
    name: "AL Downtown",
    logo: null,
    primaryColor: "#0f1117",
    accentColor: "#6c47ff",
    font: "default",
  },

  hero: {
    headline: "Webbsidor som syns – i hela Sverige",
    subheadline: "Vi bygger snabba, SEO-optimerade webbsidor för småföretag. Kreativ design med erfarenhet sedan 2019 – levererat snabbt, utan krångel.",
    cta: {
      primary: {
        text: "Ring oss nu",
        href: "tel:",
      },
      secondary: {
        text: "Skicka förfrågan",
        href: "#kontakt",
      },
    },
    image: null,
    badge: null,
  },

  about: {
    title: "Digitalbyrån som levererar – snabbt och kreativt",
    body: "AL Downtown är en digital byrå med rötter sedan 2019. Vi hjälper småföretag i hela Sverige att synas online med webbsidor som laddar snabbt, rankar högt i Google och ser professionella ut. Hos oss får du en erfaren partner som förstår ditt företag – inte en stor byrå som behandlar dig som ett ärendenummer.",
    secondaryBody: null,
    founded: "2019",
    teamSize: "3",
    stats: [
      { value: "6+", label: "ÅRS ERFARENHET" },
      { value: "3", label: "DEDIKERADE EXPERTER" },
      { value: "15 000", label: "KR SNITTUPPDRAG" },
    ],
    image: null,
    slug: "om-oss",
    pageTitle: "Om AL Downtown — Digital byrå för småföretag",
    pageDescription: "Lär känna AL Downtown – en kreativ digitalbyrå som sedan 2019 hjälper svenska småföretag med webbdesign, SEO och digital marknadsföring.",
    sections: [
      {
        heading: "Vår historia",
        body: "AL Downtown grundades 2019 med ett tydligt mål: att ge småföretag tillgång till samma digitala kvalitet som de stora bolagen – utan den stora prislappen. Sedan dess har vi byggt webbsidor och digitala lösningar för företag i hela Sverige, från enskilda hantverkare till växande tjänsteföretag.",
      },
      {
        heading: "Så jobbar vi",
        body: "Vi börjar alltid med att förstå ditt företag och dina kunder. Sedan designar och bygger vi en sajt som inte bara ser bra ut – den ska ladda snabbt, vara optimerad för sökmotorer och fungera felfritt på alla enheter. Vi håller dig uppdaterad längs vägen och levererar i tid.",
      },
      {
        heading: "Vårt serviceområde",
        body: "Vi jobbar med kunder i hela Sverige – från Malmö till Umeå. Eftersom vi arbetar digitalt spelar geografin ingen roll. Möten sker enkelt via video och allt material hanteras online.",
      },
    ],
  },

  services: [
    {
      title: "Webbdesign",
      description: "Vi designar och bygger webbsidor som ser professionella ut, laddar blixtsnabbt och är byggda för att ranka bra i Google – från dag ett.",
      icon: "build",
      slug: "webbdesign",
      pageTitle: "Webbdesign för småföretag i hela Sverige",
      pageDescription: "AL Downtown skapar snabba, mobilanpassade webbsidor för svenska småföretag. SEO-optimerade från start och levererade utan onödigt krångel.",
      preamble: "En webbsida från AL Downtown är inte bara snygg – den är byggd för att prestera. Snabb, sökmotorvänlig och anpassad för ditt företag.",
      heroImage: null,
      sections: [
        {
          heading: "En sajt som jobbar för dig dygnet runt",
          body: "Din webbsida är ofta det första intrycket en potentiell kund får av ditt företag. Vi designar sajter som speglar din identitet, bygger förtroende och gör det enkelt för besökare att ta kontakt. Varje sida vi bygger är mobilanpassad, tillgänglighetsanpassad och optimerad för hastighet.",
        },
        {
          heading: "Byggt för SEO och AI-sökning",
          body: "Sökmotoroptimering är inget vi lägger till efteråt – det är inbyggt i hur vi kodar och strukturerar din sajt från start. Vi ser till att din sida syns när dina kunder söker efter dina tjänster, oavsett om de använder Google eller AI-baserade söktjänster.",
        },
      ],
      highlights: [
        { title: "Snabb leverans", description: "Vi levererar färdiga webbsidor effektivt utan att kompromissa med kvaliteten." },
        { title: "SEO-optimerad från start", description: "Rätt struktur, rätt metadata och rätt hastighet – inbyggt från dag ett." },
        { title: "Mobilanpassad design", description: "Din sajt fungerar perfekt på telefon, surfplatta och dator." },
        { title: "AI-redo struktur", description: "Vi bygger sajter som förstås och indexeras korrekt av moderna AI-sökmotorer." },
        { title: "Transparent prissättning", description: "Inga dolda avgifter – du vet vad du betalar för innan vi sätter igång." },
      ],
      faq: [
        { question: "Hur lång tid tar det att bygga en webbsida?", answer: "Det beror på uppdragets storlek, men en enklare företagssajt levererar vi vanligtvis inom 2–4 veckor från det att vi fått allt material." },
        { question: "Vad kostar en webbsida hos AL Downtown?", answer: "Våra webbprojekt börjar vanligtvis runt 15 000 kr. Det exakta priset beror på antal sidor, funktioner och design. Kontakta oss för en kostnadsfri offert." },
        { question: "Kan ni göra om min befintliga webbsida?", answer: "Absolut. Vi gör redesigns och förbättringar av befintliga sajter lika gärna som vi bygger nytt från grunden." },
        { question: "Är webbsidan mobilanpassad?", answer: "Ja, alla sajter vi bygger är responsiva och fungerar felfritt på alla skärmstorlekar." },
        { question: "Kan jag redigera sajten själv efteråt?", answer: "Vi sätter upp din sajt med ett användarvänligt CMS så att du enkelt kan uppdatera text och bilder utan teknisk kunskap." },
      ],
    },
    {
      title: "Grafisk design",
      description: "Logotyper, grafisk profil och visuell identitet som gör ditt varumärke minnesvärt och trovärdigt – oavsett var du möter kunden.",
      icon: "paint",
      slug: "grafisk-design",
      pageTitle: "Grafisk design för småföretag i hela Sverige",
      pageDescription: "AL Downtown skapar grafiska profiler, logotyper och visuella identiteter för svenska småföretag. Kreativ design med strategiskt tänk.",
      preamble: "Din visuella identitet är grunden för allt du kommunicerar. Vi hjälper dig att se professionell och konsekvent ut – oavsett kanal.",
      heroImage: null,
      sections: [
        {
          heading: "Varumärke som skapar förtroende",
          body: "En stark grafisk identitet handlar om mer än en snygg logotyp. Det handlar om att skapa en helhetskänsla som dina kunder känner igen och litar på. Vi designar med strategi i ryggen – färger, typografi och grafiska element som kommunicerar rätt sak om ditt företag.",
        },
        {
          heading: "Från idé till färdig profil",
          body: "Vi tar dig igenom hela processen – från idéfas och moodboards till leverans av kompletta designfiler i alla format du behöver. Du får en grafisk manual som gör det enkelt att använda din identitet konsekvent framåt.",
        },
      ],
      highlights: [
        { title: "Logotyp i alla format", description: "Du får färdiga filer för webb, print och sociala medier." },
        { title: "Komplett grafisk manual", description: "Tydliga riktlinjer för hur du använder din identitet konsekvent." },
        { title: "Strategisk design", description: "Vi designar inte bara snyggt – vi designar med ditt affärsmål i åtanke." },
        { title: "Kreativt med erfarenhet", description: "Över sex års erfarenhet av att skapa varumärken för svenska småföretag." },
      ],
      faq: [
        { question: "Vad ingår i en grafisk profil?", answer: "En grafisk profil hos oss inkluderar vanligtvis logotyp, färgpalett, typografi, grafiska element och en enkel manual för hur allt används." },
        { question: "Hur lång tid tar det att få en logotyp?", answer: "Vi levererar logotypförslag inom ca en vecka. Tillsammans finjusterar vi sedan tills du är helt nöjd." },
        { question: "Kan ni uppdatera min befintliga logotyp?", answer: "Ja, vi kan både modernisera och förfina din nuvarande logotyp om du inte vill byta helt." },
        { question: "Vad kostar grafisk design?", answer: "Kontakta oss för en skräddarsydd offert baserad på vad du behöver. Vi är transparenta med priser och inga dolda kostnader tillkommer." },
      ],
    },
    {
      title: "Digital marknadsföring & konsultation",
      description: "Strategisk rådgivning och praktisk hjälp med digital marknadsföring – så att fler av rätt kunder hittar ditt företag online.",
      icon: "electric",
      slug: "digital-marknadsforing",
      pageTitle: "Digital marknadsföring för småföretag i hela Sverige",
      pageDescription: "AL Downtown erbjuder konsultation och strategisk digital marknadsföring för svenska småföretag. SEO, innehåll och synlighet – vi hjälper dig växa online.",
      preamble: "Att ha en bra webbsida räcker inte – du behöver också synas. Vi hjälper dig med strategin och genomförandet som tar ditt företag framåt digitalt.",
      heroImage: null,
      sections: [
        {
          heading: "Syns du inte online, finns du inte",
          body: "Dina kunder söker efter dina tjänster på Google varje dag. Frågan är om de hittar dig – eller dina konkurrenter. Vi hjälper dig att förstå var du befinner dig digitalt och vad du behöver göra för att klättra uppåt i sökresultaten.",
        },
        {
          heading: "Konsultation som ger konkreta resultat",
          body: "Vi erbjuder inte luddiga strategidokument – vi ger dig konkret vägledning och handlingsplaner. Vare sig du behöver hjälp med SEO, innehållsstrategi, Google Business eller annonsering tar vi dig igenom vad som faktiskt fungerar för ett företag som ditt.",
        },
      ],
      highlights: [
        { title: "SEO-strategi för småföretag", description: "Vi fokuserar på lokala och nischade söktermer som ger dig relevanta kunder." },
        { title: "Google Business-optimering", description: "Vi ser till att ditt företag syns rätt i Googles lokala sökresultat." },
        { title: "Innehållsrådgivning", description: "Vi hjälper dig skapa innehåll som rankar och bygger förtroende hos kunderna." },
        { title: "AI-sökning i fokus", description: "Vi förbereder din digitala närvaro för hur AI-verktyg indexerar och presenterar företag." },
        { title: "Inga långa bindningstider", description: "Vi erbjuder flexibla konsultpaket utan långa kontrakt." },
      ],
      faq: [
        { question: "Vad är SEO och varför behöver mitt företag det?", answer: "SEO (sökmotoroptimering) innebär att din webbsida syns högt upp i Google när potentiella kunder söker efter dina tjänster. Utan SEO riskerar du att vara osynlig online." },
        { question: "Hur lång tid tar det innan SEO ger resultat?", answer: "SEO är en långsiktig investering. Vanligtvis ser man tydliga förbättringar inom 3–6 månader, beroende på konkurrens och nuläge." },
        { question: "Kan ni hjälpa oss med sociala medier?", answer: "Ja, vi ger råd om strategi för sociala medier och kan hjälpa till med innehållsplanering kopplat till era övriga digitala kanaler." },
        { question: "Vad innebär AI-redo marknadsföring?", answer: "AI-söktjänster som ChatGPT och Googles AI-svar indexerar din sajt annorlunda än traditionella sökmotorer. Vi optimerar din närvaro för båda." },
        { question: "Erbjuder ni löpande konsultation?", answer: "Ja, vi erbjuder både engångsinsatser och löpande konsultuppdrag beroende på vad som passar ditt företag bäst." },
      ],
    },
  ],

  usps: [
    {
      title: "Snabb leverans, inga ursäkter",
      description: "Vi respekterar din tid och dina deadlines – du får din webbsida eller design levererad i tid, varje gång.",
    },
    {
      title: "SEO och AI inbyggt från start",
      description: "Vi bygger sajter som syns i Google och förstås av moderna AI-söktjänster – utan att du behöver tänka på det i efterhand.",
    },
    {
      title: "Kreativt med sex års erfarenhet",
      description: "Sedan 2019 har vi hjälpt svenska småföretag att se professionella ut och växa digitalt – vi vet vad som fungerar.",
    },
  ],

  references: [
    {
      title: "Webbsida, RVBM",
      description: "Vi byggde en modern, snabb webbsida åt RVBM med fokus på tydlig struktur och SEO-optimerat innehåll.",
      image: null,
    },
    {
      title: "Komplett digital profil, Studio Ouro",
      description: "Design och webbutveckling för Studio Ouro – en visuellt stark sajt med hög prestanda och tydlig konverteringsstrategi.",
      image: null,
    },
    {
      title: "Webbsida, Åkes Bygg",
      description: "Webbdesign och digital närvaro för Åkes Bygg – en enkel och trovärdig sajt som hjälper dem att ta in fler jobb online.",
      image: null,
    },
  ],

  reviews: {
    score: null,
    count: null,
    platform: "Google",
    url: null,
    show: false,
    testimonials: [
      {
        name: "Marcus B.",
        text: "AL Downtown levererade en snygg och snabb sajt på kortare tid än vi trott var möjligt. Väldigt proffsigt bemötande och bra koll på SEO.",
      },
      {
        name: "Sara J.",
        text: "Vi fick hjälp med både logotyp och webbsida. Resultatet var över förväntan och vi märker redan att fler kunder hittar oss via Google.",
      },
    ],
  },

  trust: {
    certifications: [],
    memberships: [],
    insurance: null,
  },

  faq: [
    {
      question: "Jobbar ni med företag i hela Sverige?",
      answer: "Ja, vi tar uppdrag från hela Sverige. Allt sköts digitalt med smidiga videomöten, så geografin spelar ingen roll.",
    },
    {
      question: "Hur mycket kostar en webbsida?",
      answer: "Våra projekt börjar vanligtvis runt 15 000 kr. Priset varierar beroende på uppdragets storlek och komplexitet. Kontakta oss för en gratis offert.",
    },
    {
      question: "Hur lång tid tar det innan min sajt är klar?",
      answer: "Vi är kända för snabb leverans. En standardsajt levereras vanligtvis inom 2–4 veckor efter att vi fått allt material och godkännt upplägg.",
    },
    {
      question: "Hjälper ni även till med uppdateringar efter lansering?",
      answer: "Ja, vi erbjuder löpande support och underhåll. Vi kan också utbilda dig att sköta enklare uppdateringar på egen hand.",
    },
    {
      question: "Vad skiljer AL Downtown från andra webbbyråer?",
      answer: "Vi kombinerar kreativ design med teknisk kompetens och genuint intresse för ditt företags tillväxt. Vi är snabba, personliga och fokuserade på resultat – inte på att göra processen längre än nödvändigt.",
    },
  ],

  contact: {
    phone: "",
    email: "info@aldowntown.com",
    address: null,
    hours: null,
    emergency: null,
    mapUrl: null,
    formEnabled: true,
  },

  social: {
    facebook: null,
    instagram: null,
  },

  footer: {
    tagline: "Webbsidor som syns – för hela Sverige",
    showCertifications: false,
    showReviews: false,
  },

  seo: {
    geo: {
      city: "Sverige",
      region: "Hela Sverige",
      country: "SE",
      lat: "59.3293",
      lng: "18.0686",
    },
    serviceArea: [
      "Stockholm",
      "Göteborg",
      "Malmö",
      "Uppsala",
      "Linköping",
      "Örebro",
      "Hela Sverige",
    ],
    keywords: [
      "webbyrå småföretag",
      "webbdesign småföretag Sverige",
      "SEO-optimerad webbsida",
      "grafisk design företag",
      "digital marknadsföring småföretag",
      "bygga hemsida snabbt",
      "webbkonsult Sverige",
    ],
    businessType: "ProfessionalService",
  },

  schema: {
    enabled: true,
    localBusiness: true,
    faqPage: true,
    breadcrumb: false,
  },

} as const;

export type ClientConfig = typeof client;
