// client.config.ts
// Generated by Claude for Härryda VVS
// Studio Ouro — 2025-02-20

export const client = {

  meta: {
    title: "Härryda VVS — Badrum & VVS-tjänster i Härryda",
    description: "Lokalt VVS-företag i Härryda sedan 2009. Vi renoverar badrum, installerar värmepumpar och rycker ut akut. Svar inom 2 timmar. ROT-godkänt. Alltid rättvisa priser.",
    language: "sv",
    token: "",
    domain: "",
  },

  brand: {
    name: "Härryda VVS",
    logo: null,
    primaryColor: "#1a2e3b",   // djup marinblå — professionell, pålitlig
    accentColor: "#e8a020",    // varm amber — lokal, varm, hantverk
    backgroundColor: "",
    textColor: "",
    titleFont: "Funnel Display",
    bodyFont: "Funnel Sans",
    mode: "light",
    radius: "soft",
    font: "default",
  },

  hero: {
    headline: "Ditt lokala VVS-företag i Härryda",
    subheadline: "Vi är ett familjärt VVS-bolag med rötter i Härryda sedan 2009. Du får svar inom 2 timmar, rättvisa priser och ett team som verkligen känner trakten.",
    cta: {
      primary: {
        text: "Ring oss nu",
        href: "tel:null",
      },
      secondary: {
        text: "Skicka förfrågan",
        href: "#kontakt",
      },
    },
    image: null,
    badge: "Behöriga VVS-installatörer",
  },

  about: {
    title: "Familjeföretaget som verkligen bryr sig",
    body: "Härryda VVS grundades 2009 och drivs av en ägare som också är projektledare — med fyra familjemedlemmar i teamet. Vi är inte ett anonymt bolag. Vi är dina grannar, och vi behandlar varje uppdrag som om det vore vårt eget hem.",
    secondaryBody: "Vi ser oss som en partner, inte bara en leverantör. Det innebär att vi ger dig ärliga råd, håller vad vi lovar och aldrig skickar en faktura du inte förstår.",
    founded: "2009",
    teamSize: "8",
    stats: [
      { value: "15+", label: "ÅRS ERFARENHET" },
      { value: "120", label: "NÖJDA GOOGLE-RECENSIONER" },
      { value: "4.5", label: "BETYG PÅ GOOGLE" },
      { value: "2h", label: "SVARSTID ALLTID" },
    ],
    image: null,
    slug: "om-oss",
    pageTitle: "Om oss — Härryda VVS",
    pageDescription: "Lär känna Härryda VVS — ett familjedrivet VVS-bolag sedan 2009 med lokal förankring i Härryda och kranskommunerna. Rättvisa priser och alltid svar inom 2 timmar.",
    sections: [
      {
        heading: "Vår historia",
        body: "Härryda VVS startade 2009 med en enkel idé: att vara det VVS-bolag i Härryda som kunder faktiskt kan lita på. Det som började som ett litet familjeföretag har vuxit till ett team på åtta personer — fyra från familjen och fyra duktiga hantverkare utifrån. Under åren har vi genomfört hundratals uppdrag i kommunen, från enstaka rörbyten till kompletta badrumsrenoveringar och storskaliga bergvärmeinstallationer.",
      },
      {
        heading: "Så jobbar vi",
        body: "Vi börjar alltid med att lyssna. Vad vill du uppnå? Vad oroar dig? Sedan ger vi dig ett tydligt, skriftligt prisförslag utan dolda avgifter. Under projektets gång håller vi dig uppdaterad, håller tidplanen och städar efter oss. Vi svarar på samtal och meddelanden inom 2 timmar — varje dag.",
      },
      {
        heading: "Vårt serviceområde",
        body: "Vi är stationerade i Härryda och utför arbeten i hela Härryda kommun samt kranskommunerna — inklusive Mölndal, Partille, Lerum och Borås-trakten. Tack vare vår starka lokala förankring och kontakter kan vi slutföra jobb snabbt och smidigt, oavsett vad projektet kräver.",
      },
    ],
  },

  services: [
    {
      title: "Badrumsrenovering",
      description: "Vi renoverar badrum från ax till limpa — rivning, kakel, rör, golvvärme och slutbesiktning. Du slipper koordinera flera hantverkare.",
      icon: "shower",
      slug: "badrumsrenovering",
      pageTitle: "Badrumsrenovering i Härryda",
      pageDescription: "Professionell badrumsrenovering i Härryda och kranskommunerna. Behöriga VVS-installatörer, ROT-avdrag och fast pris. Svar inom 2 timmar.",
      preamble: "Ett nytt badrum ska kännas tryggt från första mötet. Vi tar hand om hela processen, ger dig ett fast pris och ser till att slutresultatet håller hög kvalitet — utan överraskningar.",
      heroImage: null,
      sections: [
        {
          heading: "Vad ingår i en badrumsrenovering?",
          body: "Vi hanterar hela projektet: rivning av gammalt kakel och golv, installation av nya rör och avlopp, tätskikt, kakling, golvvärme, sanitetsporslin och slutbesiktning. Du har en kontaktperson genom hela projektet.",
        },
        {
          heading: "ROT-avdrag och behörighet",
          body: "Som behöriga VVS-installatörer och ROT-godkänt företag kan vi hantera ROT-avdraget åt dig direkt mot Skatteverket. Det innebär att du bara betalar halva arbetskostnaden — vi sköter pappersarbetet.",
        },
      ],
      highlights: [
        { title: "Fast pris", description: "Vi lämnar alltid ett tydligt prisförslag innan arbetet börjar — inga dolda kostnader." },
        { title: "ROT-avdrag", description: "Vi hanterar ROT-ansökan direkt, du betalar bara 50% av arbetskostnaden." },
        { title: "Behöriga installatörer", description: "Allt VVS-arbete utförs av certifierade och behöriga VVS-installatörer." },
        { title: "En kontaktpunkt", description: "Du slipper koordinera flera hantverkare — vi sköter hela renoveringen." },
        { title: "Garanti på arbetet", description: "Vi står bakom vårt arbete och åtgärdar eventuella fel utan extra kostnad." },
      ],
      faq: [
        { question: "Hur lång tid tar en badrumsrenovering?", answer: "En typisk badrumsrenovering tar 2–4 veckor beroende på storlek och vad som ingår. Vi ger dig en tydlig tidplan innan vi börjar." },
        { question: "Kan jag få ROT-avdrag på badrumsrenovering?", answer: "Ja, arbetskostnaden berättigar till ROT-avdrag. Vi hanterar ansökan åt dig direkt mot Skatteverket." },
        { question: "Vad kostar en badrumsrenovering i Härryda?", answer: "Priset varierar beroende på storlek och materialval, men ett genomsnittligt projekt ligger kring 50 000 kr. Vi ger alltid ett fast, skriftligt offertpris." },
        { question: "Hanterar ni hela renoveringen eller bara röret?", answer: "Vi hanterar hela projektet — rivning, kakel, rör, golvvärme och sanitet. Du behöver inte anlita flera firmor." },
        { question: "Jobbar ni i hela Härryda kommun?", answer: "Ja, vi jobbar i hela Härryda med kranskommuner som Mölndal, Partille och Lerum." },
      ],
    },
    {
      title: "Värmepumpsinstallation",
      description: "Vi installerar berg-, luft- och frånluftsvärmepumpar för villor och fastigheter. Sänk din energikostnad med rätt installation från certifierade proffs.",
      icon: "heat",
      slug: "varmepumpsinstallation",
      pageTitle: "Värmepumpsinstallation i Härryda",
      pageDescription: "Certifierad värmepumpsinstallation i Härryda. Vi installerade bergvärme för 50 fastigheter i Skinnefjäll. ROT-avdrag. Svar inom 2 timmar.",
      preamble: "Rätt värmepump kan halvera dina uppvärmningskostnader. Vi har installerat bergvärme i hela bostadsområden och vet vad som krävs för ett korrekt utfört jobb.",
      heroImage: null,
      sections: [
        {
          heading: "Berg-, luft- eller frånluftsvärmepump?",
          body: "Valet av värmepump beror på din fastighets förutsättningar. Vi gör en bedömning av ditt hem och rekommenderar den lösning som ger bäst avkastning på investeringen — utan att sälja på dig mer än du behöver.",
        },
        {
          heading: "Referens: Skinnefjäll, Mölnlycke",
          body: "Vi installerade bergvärme för 50 fastigheter i Skinnefjäll i Mölnlycke — ett av våra största och mest komplexa uppdrag. Projektet genomfördes i tid och utan störningar för de boende.",
        },
      ],
      highlights: [
        { title: "Certifierade installatörer", description: "Vi är behöriga att installera alla typer av värmepumpar för villor och fastigheter." },
        { title: "Beprövade i stor skala", description: "Vi har installerat bergvärme för hela bostadskvarter — vi vet vad vi gör." },
        { title: "ROT-avdrag", description: "Installation av värmepump berättigar till ROT-avdrag på arbetskostnaden." },
        { title: "Rådgivning utan säljtryck", description: "Vi rekommenderar det som passar din villa — inte det dyraste alternativet." },
        { title: "Lokal service", description: "Som lokalt företag finns vi nära till hands för service och uppföljning efter installation." },
      ],
      faq: [
        { question: "Vad kostar en bergvärmepumpsinstallation?", answer: "En bergvärmepumpsinstallation kostar typiskt 120 000–200 000 kr beroende på hustype och borrhålsdjup. Vi ger alltid ett fast offertpris." },
        { question: "Kan jag få ROT-avdrag på värmepumpsinstallation?", answer: "Ja, arbetskostnaden för installation berättigar till ROT-avdrag. Vi hanterar ansökan åt dig." },
        { question: "Hur lång tid tar installationen?", answer: "En typisk värmepumpsinstallation tar 3–7 dagar. Vi planerar in arbetet så att störningen för dig minimeras." },
        { question: "Vilka typer av värmepumpar installerar ni?", answer: "Vi installerar bergvärme, luftvärmepumpar och frånluftsvärmepumpar för villor och flerbostadshus." },
        { question: "Jobbar ni med bostadsrättsföreningar och kommuner?", answer: "Ja, vi har erfarenhet av storskaliga projekt för både kommuner och bostadsföreningar." },
      ],
    },
    {
      title: "Akut VVS",
      description: "Vattenläcka, stopp eller trasig varmvattenberedare? Vi rycker ut snabbt i Härryda och kranskommunerna — svar garanterat inom 2 timmar.",
      icon: "emergency",
      slug: "akut-vvs",
      pageTitle: "Akut VVS i Härryda",
      pageDescription: "Akut VVS-hjälp i Härryda och kranskommunerna. Vi svarar inom 2 timmar. Behöriga installatörer. Inga dolda jourtillägg.",
      preamble: "En vattenläcka väntar inte. Vi heller inte. Ring oss och du får svar inom 2 timmar — dygnet runt gäller vid akuta situationer.",
      heroImage: null,
      sections: [
        {
          heading: "Vanliga akuta VVS-situationer",
          body: "Vi hanterar alla typer av akuta VVS-ärenden: vattenläckor, rörbrott, stopp i avlopp, trasiga varmvattenberedare och vattenskador. Vi bedömer situationen snabbt och sätter igång åtgärderna direkt.",
        },
        {
          heading: "Vad gör du när det läcker?",
          body: "Stäng av vattnet vid huvudkranen och ring oss direkt. Vi guidar dig i telefon och skickar ut rätt person med rätt utrustning. Du betalar aldrig för mer tid än vad som faktiskt krävs.",
        },
      ],
      highlights: [
        { title: "Svar inom 2 timmar", description: "Vi garanterar återkoppling inom 2 timmar — alltid." },
        { title: "Lokal närvaro", description: "Vi är baserade i Härryda och kan vara på plats snabbt." },
        { title: "Inga dolda avgifter", description: "Vi är transparenta med priset även vid akututryckningar." },
        { title: "Behöriga installatörer", description: "Alla åtgärder utförs av certifierade VVS-proffs." },
      ],
      faq: [
        { question: "Hur snabbt kan ni vara på plats vid en vattenläcka?", answer: "Vi svarar alltid inom 2 timmar. Utryckningstiden beror på var i Härryda eller kranskommunerna du befinner dig." },
        { question: "Vad ska jag göra medan jag väntar på er?", answer: "Stäng av vattnet vid huvudkranen om möjligt. Vi guidar dig gärna i telefon tills vi är på plats." },
        { question: "Kostar det extra för akututryckning?", answer: "Vi är alltid transparenta med priset. Vi informerar dig om eventuellt jourtillägg innan vi åker ut." },
        { question: "Jobbar ni på helger och kvällar?", answer: "Vi prioriterar akuta ärenden och svarar inom 2 timmar även utanför kontorstid." },
        { question: "Vilka akuta VVS-problem hanterar ni?", answer: "Vi hanterar vattenläckor, rörbrott, avloppsstopp, trasiga vattenberedare och övriga akuta VVS-situationer." },
      ],
    },
    {
      title: "Fastighetskötsel",
      description: "Löpande underhåll och skötsel av VVS-system för villor, fastigheter och kommunala byggnader i Härryda.",
      icon: "wrench",
      slug: "fastighetskotsel",
      pageTitle: "Fastighetskötsel i Härryda",
      pageDescription: "Professionell fastighetskötsel i Härryda. Löpande VVS-underhåll för villor, bostadsrättsföreningar och kommuner. Lokalt och pålitligt sedan 2009.",
      preamble: "Förebygg problem innan de uppstår. Vi erbjuder löpande fastighetskötsel anpassad efter dina behov — från enstaka servicebesök till helårskavtal.",
      heroImage: null,
      sections: [
        {
          heading: "Vad ingår i fastighetsskötseln?",
          body: "Vi erbjuder regelbunden kontroll och underhåll av VVS-installationer, värmesystem, varmvattenberedare och avlopp. Tjänsten anpassas efter din fastighet och kan inkludera allt från månadsbesök till årsavtal med prioriterad service.",
        },
        {
          heading: "För kommuner och bostadsföreningar",
          body: "Vi har erfarenhet av att arbeta med kommunala uppdragsgivare och bostadsrättsföreningar i Härryda. Vi förstår kraven på dokumentation, tillgänglighet och pålitlighet som större uppdragsgivare ställer.",
        },
      ],
      highlights: [
        { title: "Förebyggande underhåll", description: "Vi hittar och åtgärdar problem innan de blir dyra." },
        { title: "Flexibla avtal", description: "Välj det upplägg som passar din fastighet — inga onödiga paket." },
        { title: "Lokal kännedom", description: "Vi känner fastigheterna i Härryda och vet vad som brukar behöva åtgärdas." },
        { title: "Pålitlig rapportering", description: "Du får alltid dokumentation på utfört arbete." },
      ],
      faq: [
        { question: "Vad kostar en fastighetskötseltjänst?", answer: "Priset beror på fastighetens storlek och vad som ingår. Vi ger ett skräddarsytt offertpris utan bindningstid." },
        { question: "Kan ni sköta fastigheter för bostadsrättsföreningar?", answer: "Ja, vi har erfarenhet av att arbeta med bostadsrättsföreningar och kommuner i Härryda och kranskommunerna." },
        { question: "Hur snabbt kan ni agera vid ett fel?", answer: "Som fastighetskund prioriteras du vid akuta ärenden och vi svarar alltid inom 2 timmar." },
        { question: "Erbjuder ni årsavtal?", answer: "Ja, vi erbjuder löpande avtal anpassade efter din fastighets behov." },
        { question: "Vad ingår i ett servicebesök?", answer: "Vi kontrollerar VVS-installationer, värmesystem och avlopp, noterar avvikelser och åtgärdar det vi hittar — eller ger dig en plan för kommande insatser." },
      ],
    },
  ],

  usps: [
    {
      title: "Svar inom 2 timmar",
      description: "Vi garanterar att du alltid får återkoppling inom 2 timmar — oavsett om det gäller en offertförfrågan eller ett akut läckagelarm.",
    },
    {
      title: "Rättvisa priser alltid",
      description: "Vi lämnar alltid ett tydligt prisförslag innan arbetet startar — inga dolda avgifter, inga överraskningar på slutfakturan.",
    },
    {
      title: "Lokalt sedan 2009",
      description: "Vi är inte ett anonymt bolag. Vi är ett familjeföretag med djupa rötter i Härryda — vi känner trakten, kunderna och de lokala förutsättningarna.",
    },
  ],

  references: [
    {
      title: "Bergvärmeinstallation, Skinnefjäll i Mölnlycke",
      description: "Vi installerade bergvärme för samtliga 50 fastigheter i Skinnefjäll — ett storskaligt projekt som genomfördes i tid och utan störningar för de boende.",
      image: null,
    },
    {
      title: "12 badrumsrenoveringar, flerbostadshus i Härryda",
      description: "Komplett renovering av 12 badrum i ett höghus i Härryda — vi samordnade hela projektet och höll tidsplanen från start till slutbesiktning.",
      image: null,
    },
  ],

  reviews: {
    score: "4.5",
    count: "120",
    platform: "Google",
    url: null,
    show: true,
    testimonials: [
      {
        name: "Magnus E.",
        text: "Extremt nöjd med min badrumsrenovering. Tydlig offert, höll tidsplanen och städade efter sig. Priset var exakt som de sa från början. Rekommenderar varmt!",
      },
      {
        name: "Birgitta K.",
        text: "Ringde på en fredag eftermiddag med en vattenläcka. De svarade inom en timme och var hemma hos mig på kvällen. Proffsigt, snabbt och schysst pris.",
      },
    ],
  },

  trust: {
    certifications: ["ROT-godkänt", "Behöriga VVS-installatörer", "F-skattsedel"],
    memberships: [],
    insurance: null,
  },

  faq: [
    {
      question: "Hur snabbt svarar ni på förfrågningar?",
      answer: "Vi svarar alltid inom 2 timmar — oavsett om det gäller en offertförfrågan, ett servicebehov eller ett akut ärende. Det är ett löfte vi håller.",
    },
    {
      question: "Kan jag använda ROT-avdrag för era tjänster?",
      answer: "Ja. Vi är ett ROT-godkänt företag och hanterar ansökan åt dig direkt mot Skatteverket. Du betalar bara 50% av arbetskostnaden.",
    },
    {
      question: "Vilka områden jobbar ni i?",
      answer: "Vi utför arbeten i hela Härryda kommun samt kranskommunerna, inklusive Mölndal, Partille och Lerum. Kontakta oss om du är osäker på om vi täcker ditt område.",
    },
    {
      question: "Är era priser fasta eller löpande räkning?",
      answer: "Vi lämnar alltid ett fast prisförslag innan arbetet börjar. Du vet vad du betalar — inga timdebiterade överraskningar efteråt.",
    },
    {
      question: "Är ni ett certifierat VVS-företag?",
      answer: "Ja. Vi är behöriga VVS-installatörer med F-skattsedel. Allt arbete utförs enligt gällande branschstandarder och myndighetskrav.",
    },
  ],

  contact: {
    phone: "031-123 45 67",
    email: "info@harrydavvs.se",
    address: "Exempelgatan 1, 433 00 Härryda",
    hours: "Mån–Fre 08:00–17:00, Lör 09:00–13:00",
    emergency: "Vid akuta VVS-ärenden — ring oss direkt. Vi svarar inom 2 timmar.",
    // Map: set to a full Google Maps embed URL to override. Else map is derived from seo.geo (lat/lng) — scraped data maps here.
    mapUrl: null,
    formEnabled: true,
  },

  social: {
    facebook: null,
    instagram: null,
  },

  footer: {
    tagline: "Ditt pålitliga VVS-företag i Härryda sedan 2009.",
    showCertifications: true,
    showReviews: true,
  },

  seo: {
    geo: {
      city: "Härryda",
      region: "Västra Götalands län",
      country: "SE",
      lat: "57.6574",
      lng: "12.2261",
    },
    serviceArea: [
      "Härryda",
      "Mölnlycke",
      "Hindås",
      "Landvetter",
      "Partille",
      "Mölndal",
      "Lerum",
    ],
    keywords: [
      "VVS Härryda",
      "badrumsrenovering Härryda",
      "värmepumpsinstallation Härryda",
      "akut VVS Härryda",
      "rörmokare Härryda",
      "badrum renovering Mölnlycke",
      "VVS företag Partille",
    ],
    businessType: "Plumber",
  },

  schema: {
    enabled: true,
    localBusiness: true,
    faqPage: true,
    breadcrumb: false,
  },

} as const;

export type ClientConfig = typeof client;
